### PR TITLE
ISS-265 smart search backend

### PR DESCRIPTION
**Pull request by l-cheung**
**Setup**
* **Requires ONET_USERNAME and ONET_PASSWORD** to be set in the `.env` file for docker (if using docker) and/or the root directory (if using virtualenv)

**Changes**
* Adds `SocListSmartViewSet` view & `soc-smart-list` endpoint, which implements a smart search for occupations
* Smart search will (1) execute an O*NET API query for a user-input keyword, (2) compare those results against available transition SOCs, and (3) return SOCs that are available and match the user-input keyword
* Adds ONET_USERNAME and ONET_PASSWORD parameters to `common.yml`

**Screenshots**
image
image
image

**Tests**
* manage.py test
* Tested with docker and virtualenv

fyi @aniyip - continuation of what we worked on last week

### CODE REVIEW

**Comment by l-cheung** [comment]
Should `Installation.md` be updated with information from `stack/Readme.md` to reflect changes to the docker setup?

**Comment by jedpittman** [comment]
Yes.

**Comment by jedpittman** [comment]
Totally solid @l-cheung . Really nice work. Merging.

**Comment by l-cheung** [comment]
:) added a couple issues to connect the the smart search backend to the frontend & update installation docs

**Comment by jedpittman** [comment]
Lilian, can you please add a new pull request/issue for your changes? I've
already merged your code.

**Comment by l-cheung** [comment]
Yeah, the issues are added already. No new code changes yet

**Pull request merged**
