### PR TITLE
ISS-55

### PR DESCRIPTION
**Pull request by pgibb96**
I would definitely appreciate someone more experienced review this to make sure I'm doing what I'm supposed to be doing. I added the model for the soc data that the data team is currently finishing up. Then I updated the serializer.py with a serializer for that model. Then I updated the api.py with the modelViewset for that model and serializer. Finally, I updated the base jobhopper url.py to direct to the jobs/url.py with just "", rather than "jobs/". Then, I changed the router in the jobs/url.py to show the soc data at [base-url]/api/v1/soc-codes, rather than the original [base-url]/**jobs**/api/v1/soc-codes. I wasn't sure which one Jed wanted so that can be changed.

### CODE REVIEW

**Comment by pgibb96** [comment]
Also, a lot of those readme changes towards the top were before Endy improved the readme. I created this branch by tracking the codeforboston/V1.0.0 branch and pulling from there to get the most recent version. Then, I did a merge request on my forked repo from my ISS-55 branch to my new V1.0.0 branch. I'm not sure why there are commits on this branch (pgibb96/jobhopper/V1.0.0) from my master branch.

**Comment by jedpittman** [comment]
I will take a look in the next day or so if someone else hasn’t reviewed before then, Thanks!

**Comment by jedpittman** [comment]
Peter, I've started on this tonight -- but I am trying to make sure everything works on my machine to ensure that we are still in a good state, verified by a couple of people. I hope to have this by the end of week -- if there's any way I can merge this in, I will. Thanks!

**Comment by pgibb96** [comment]
Thanks Jed!

**Comment by jedpittman** [comment]
Manually resolved conflicts; 
Ensured tests ran as expected afterward:

(venv) C:\Users\jedpi\OneDrive\Documents\GitHub>python ISS-55/jobhopper/manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..
----------------------------------------------------------------------
Ran 2 tests in 0.040s

OK
Destroying test database for alias 'default'...

**Pull request merged**
