### PR TITLE
Fix formatting and set min transition rate to 0.2%

### PR DESCRIPTION
**Pull request by alexjball**
Units, man...

### CODE REVIEW

**Comment by jedpittman** [comment]
@alexjball what issue is this related to and are we sure that this works with the changes Lilian is putting in for the data? I am holding this until I hear back from you and/or I have a chance to test this with Lilian's work.

**Comment by alexjball** [comment]
@jedpittman I've tested this with LIlian's work. Based on my reading of the dataset, the transition rate is represented as a proportion of the total transitions out of the occupation, so a rate of .01 represents a transition of 1%. @l-cheung does that sound correct?

I believe this has always been the case and the existing code is bugged. This is consistent with Anna's comment that our data displayed transitions 10x smaller than hers.

**Comment by l-cheung** [comment]
That's correct! In the paper, the transition rate is defined as the probability that someone transitions to occupation_2, given that they left occupation_1. It's expressed as a proportion in the transitions dataset, so 0.01 is 1% and 0.002 is 0.2%.

This would fix https://github.com/codeforboston/jobhopper/issues/255

**Comment by jedpittman** [comment]
merging per alex/lillian

**Pull request merged**
