### PR TITLE
Treemap redesign - popups and category key

### LINKED ISSUE #298: Treemap Redesign Part 2 - Add Category Key (this is current next item for sasha)
Split from #273 
Refer to #252 and #253 with information for layout then....
Create a design/mockup for the treemap that incorporates the following:

DOD:
* **There should be a key which explains to users easily which group maps to which color (major occupation group names may need to be shortened for ease of viewing in the key!).**

### PR DESCRIPTION
**Pull request by sashamaryl**
Closes #298

adds highlighted category key
colors boxes by category
component organization (adds treemap wrapper, moves small components to shared file)
adds information pop-ups to treemap

### CODE REVIEW

**Comment by jedpittman** [comment]
sent a message to @sashamaryl  on slack about these. Not merging because they are too far out of sync with develop branch.

**Comment by sashamaryl** [comment]
@jedpittman 
working on this with Alex -- hope to be ready next week

**Review by alexjball — APPROVED** [review]
:100: :fire: :rocket: :tada: !

We should squash and merge this

**Comment by jedpittman** [comment]
Closes #298 and @alexjball  has reviewed. Merging.

**Pull request merged**
