### PR TITLE
Clean BLS data and add it to the API

### PR DESCRIPTION
**Pull request by volunteer-a-thon**
The data group looked into the BLS data available to determine whether additional data cleaning was necessary & added the cleaned dataset to the API.
* The dataset included many duplicate location-OCC codes, with wages/employment differing by industry (NAICS code). We filtered down the dataset to only look across all industries.
* We excluded MSAs, leaving statewide and national data
* We added the ability to pull in multiple years' worth of BLS data. The datasets will download the Excel file first, then convert it to a csv (so the first time the dataset is loaded will take much longer than subsequent runs).

Migrations output:
```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jobs, sessions
Running migrations:
  Applying jobs.0001_initial... OK
  Applying jobs.0002_occupationtransitions... OK
  Applying jobs.0003_auto_20200909_1254... OK
  Applying jobs.0004_auto_20200909_1255... OK
  Applying jobs.0005_auto_20200914_1220... OK
  Applying jobs.0006_blsoesfakes... OK
  Applying jobs.0007_stateabbpairs... OK
  Applying jobs.0008_auto_20201006_AddStateData... OK
  Applying jobs.0009_auto_20201013_2033... OK
  Applying jobs.0010_blsoes... OK
2020-10-29 23:44:24,762 Loading BLS wage and employment data to Postgres if a table_name is specified
2020-10-29 23:44:24,762 Connecting to Postgres DB via SQLAlchemy
2020-10-29 23:44:24,774 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:44:24,775 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:44:24,776 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:44:25,259 Download path: https://www.bls.gov//oes/special.requests/oesm18all.zip
2020-10-29 23:44:25,260 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm18all.zip if it has not been downloaded already
2020-10-29 23:44:25,305 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-10-29 23:44:25,306 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
2020-10-29 23:44:25,323 Download path: https://www.bls.gov//oes/special.requests/oesm17all.zip
2020-10-29 23:44:25,324 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm17all.zip if it has not been downloaded already
2020-10-29 23:44:25,684 OES data year 2018 was found in /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads/oesm18all/all_data_M_2018.csv. Loading it in.
2020-10-29 23:44:25,696 OES data year 2019 was found in /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads/oesm19all/all_data_M_2019.csv. Loading it in.
2020-10-29 23:44:25,723 OES data year 2017 was found in /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads/oesm17all/all_data_M_2017.csv. Loading it in.
2020-10-29 23:44:25,861 Successfully read OES data. Writing to the jobs_blsoes table
2020-10-29 23:44:29,706 Successfully loaded BLS data to Postgres!
  Applying jobs.0011_auto_20201024_2201...Done with forward load
 OK
```

Test output:
```
Creating test database for alias 'default'...
2020-10-29 23:44:36,748 Loading BLS wage and employment data to Postgres if a table_name is specified
2020-10-29 23:44:36,748 Connecting to Postgres DB via SQLAlchemy
2020-10-29 23:44:36,761 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:44:36,762 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:44:36,762 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:44:36,901 Download path: https://www.bls.gov//oes/special.requests/oesm17all.zip
2020-10-29 23:44:36,902 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm17all.zip if it has not been downloaded already
2020-10-29 23:44:36,916 Download path: https://www.bls.gov//oes/special.requests/oesm18all.zip
2020-10-29 23:44:36,917 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm18all.zip if it has not been downloaded already
2020-10-29 23:44:36,930 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-10-29 23:44:36,931 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
2020-10-29 23:44:37,104 OES data year 2019 was found in /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads/oesm19all/all_data_M_2019.csv. Loading it in.
2020-10-29 23:44:37,110 OES data year 2017 was found in /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads/oesm17all/all_data_M_2017.csv. Loading it in.
2020-10-29 23:44:37,112 OES data year 2018 was found in /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads/oesm18all/all_data_M_2018.csv. Loading it in.
2020-10-29 23:44:37,268 Successfully read OES data. Writing to the jobs_blsoes table
2020-10-29 23:44:41,200 Successfully loaded BLS data to Postgres!
Done with forward load
System check identified no issues (0 silenced).
.2020-10-29 23:44:41,403 Not Found: /jobs/api/leads
...
----------------------------------------------------------------------
Ran 4 tests in 0.037s

OK
```

Test output with no files downloaded:
```
Creating test database for alias 'default'...
2020-10-29 23:45:04,004 Loading BLS wage and employment data to Postgres if a table_name is specified
2020-10-29 23:45:04,004 Connecting to Postgres DB via SQLAlchemy
2020-10-29 23:45:04,018 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:45:04,019 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:45:04,019 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-29 23:45:04,201 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-10-29 23:45:04,202 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
2020-10-29 23:45:04,216 Download path: https://www.bls.gov//oes/special.requests/oesm18all.zip
2020-10-29 23:45:04,216 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm18all.zip if it has not been downloaded already
2020-10-29 23:45:04,229 Download path: https://www.bls.gov//oes/special.requests/oesm17all.zip
2020-10-29 23:45:04,230 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm17all.zip if it has not been downloaded already
2020-10-29 23:45:17,293 Downloading to directory /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads
2020-10-29 23:45:17,294 Downloading to directory /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads
2020-10-29 23:45:17,748 Files found: ['oesm18all/all_data_M_2018.xlsx']
2020-10-29 23:45:17,748 Check the data/bls/downloads directory for the xlsx file downloaded
2020-10-29 23:45:17,748 Reading Excel file: oesm18all/all_data_M_2018.xlsx --- This may take a few minutes.
2020-10-29 23:45:17,853 Files found: ['oesm17all/all_data_M_2017.xlsx']
2020-10-29 23:45:17,853 Check the data/bls/downloads directory for the xlsx file downloaded
2020-10-29 23:45:17,853 Reading Excel file: oesm17all/all_data_M_2017.xlsx --- This may take a few minutes.
2020-10-29 23:45:21,912 Downloading to directory /Users/lilian.cheung/Documents/Code for Boston/jobhopper/data/bls/downloads
2020-10-29 23:46:09,116 Files found: ['oesm19all/all_data_M_2019.xlsx']
2020-10-29 23:46:09,123 Check the data/bls/downloads directory for the xlsx file downloaded
2020-10-29 23:46:09,123 Reading Excel file: oesm19all/all_data_M_2019.xlsx --- This may take a few minutes.
2020-10-29 23:48:04,283 Cleaning file and saving as a csv for faster loading in future runs.
2020-10-29 23:48:27,963 Cleaning file and saving as a csv for faster loading in future runs.
2020-10-29 23:48:59,474 Cleaning file and saving as a csv for faster loading in future runs.
2020-10-29 23:49:00,083 Successfully read OES data. Writing to the jobs_blsoes table
2020-10-29 23:49:04,886 Successfully loaded BLS data to Postgres!
Done with forward load
System check identified no issues (0 silenced).
.2020-10-29 23:49:05,184 Not Found: /jobs/api/leads
...
----------------------------------------------------------------------
Ran 4 tests in 0.044s

OK
Destroying test database for alias 'default'...
```

### CODE REVIEW

**Comment by l-cheung** [comment]
Has conflicts from #174, will resolve this weekend

**Comment by jedpittman** [comment]
@l-cheung I am not sure if we wanted to filter out MSAs. I think that these are supposed to be included. @edward-malouf , can you comment on this before we merge?

**Comment by l-cheung** [comment]
Happy to change this to include them if we want to have wage/employment data at the Metropolitan area/Nonmetropolitan area level. Level of granularity: https://www.bls.gov/oes/current/msa_def.htm

**Comment by l-cheung** [comment]
Resolved conflicts & edited filtering to include MSAs and all other locations. Edited to include BLS data from 2018 and 2019. 2019 BLS wage/employment data does not cover 132 SOC codes from the (2010) occupation transitions dataset. Including 2018 reduces that number to 39 SOC codes not covered. The most recent record for SOC code and location is used.

Tests:
```
Creating test database for alias 'default'...
 show db default
Processing data from csv; This will take a few minutes.
<connection object at 0x7f88a2d545d0; dsn: 'user=jobuser password=xxx dbname=test_jobhopperdatabase host=127.0.0.1 port=5432', closed: 0>
test_jobhopperdatabase
2020-11-01 21:38:43,752 Loading occupation transitions (Burning Glass) data to Postgres
2020-11-01 21:38:43,752 Connecting to Postgres DB via SQLAlchemy
done with forward load
2020-11-01 21:39:05,438 Loading BLS wage and employment data to Postgres if a table_name is specified
2020-11-01 21:39:05,439 Connecting to Postgres DB via SQLAlchemy
2020-11-01 21:39:05,440 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-11-01 21:39:05,440 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-11-01 21:39:05,619 Download path: https://www.bls.gov//oes/special.requests/oesm18all.zip
2020-11-01 21:39:05,620 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm18all.zip if it has not been downloaded already
2020-11-01 21:39:05,706 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-11-01 21:39:05,707 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
2020-11-01 21:39:05,965 OES data year 2018 was found in /Users/lilian/Documents/jobhopper/data/bls/downloads/oesm18all/all_data_M_2018.csv. Loading it in.
2020-11-01 21:39:06,039 OES data year 2019 was found in /Users/lilian/Documents/jobhopper/data/bls/downloads/oesm19all/all_data_M_2019.csv. Loading it in.
2020-11-01 21:39:06,641 Successfully read OES data. Writing to the jobs_blsoes table
2020-11-01 21:39:32,599 Successfully loaded BLS data to Postgres!
Done with forward load
System check identified no issues (0 silenced).
.2020-11-01 21:39:42,331 Not Found: /jobs/api/leads
...
----------------------------------------------------------------------
Ran 4 tests in 0.074s

OK
Destroying test database for alias 'default'...
```

**Pull request merged**
