### PR TITLE
Update occupation transitions dataset with Jan 2021 version

### PR DESCRIPTION
**Pull request by l-cheung**
# Changelog
* Update `occupation_transitions_data_set.csv` with the latest version from Anna
* Replace the unused `soc_structure_2018.csv` file with `soc_hierarchy.xlsx` from Anna
* Edit load process for occupation_transitions dataset to account for new `transitions_share` column, which still represents the conditional probability `pi`
* Filter `soc_list` to only include source SOCs from the occupation transitions dataset
* Keep the API response similar to before, with `pi` representing the transitions share proportion
* Remove the unused `"occleaveshare", "total_soc"` fields from the transitions-extended response
* Transitions-extended endpoint returns the following (matches original format expected from this endpoint, other than excluded fields):
```
{
  "source_soc": {
    "source_soc_id": 242047,
    "source_soc_area_title": "U.S.",
    "source_soc_soc_code": "13-2011",
    "source_soc_soc_title": "Accountants and Auditors",
    "source_soc_hourly_mean_wage": 38.23,
    "source_soc_annual_mean_wage": 79520,
    "source_soc_total_employment": 1280700,
    "source_soc_soc_decimal_code": "13-2011.00",
    "source_soc_file_year": 2019
  },
  "transition_rows": [
    {
      "id": 1,
      "soc1": "13-2011",
      "soc2": "11-3031",
      "pi": 0.1782961,
      "soc2_id": 241905,
      "soc2_area_title": "U.S.",
      "soc2_soc_code": "11-3031",
      "soc2_soc_title": "Financial Managers",
      "soc2_hourly_mean_wage": 70.93,
      "soc2_annual_mean_wage": 147530,
      "soc2_total_employment": 654790,
      "soc2_soc_decimal_code": "11-3031.00",
      "soc2_file_year": 2019
    },
```
* Remove old readme

# Incorporating into Backend

* Re-run migrations to incorporate the dataset changes into the hosted backend

# Tests
* From `api directory`
```
(jobhopper) lilian@Lilians-MacBook-Pro api % python manage.py test    
Creating test database for alias 'default'...
 show db default
Processing data from csv; This will take a few minutes.
<connection object at 0x7f7f9af09470; dsn: 'user=jobuser password=xxx dbname=test_jobhopperdatabase host=127.0.0.1 port=5432', closed: 0>
test_jobhopperdatabase
2021-01-09 16:45:56,471 Loading occupation transitions (Burning Glass) data to Postgres
2021-01-09 16:45:56,472 Connecting to Postgres DB via SQLAlchemy
done with forward load
2021-01-09 16:46:27,594 Loading BLS wage and employment data to Postgres if a table_name is specified
2021-01-09 16:46:27,594 Connecting to Postgres DB via SQLAlchemy
2021-01-09 16:46:27,595 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2021-01-09 16:46:27,595 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2021-01-09 16:46:27,763 Download path: https://www.bls.gov//oes/special.requests/oesm18all.zip
2021-01-09 16:46:27,764 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm18all.zip if it has not been downloaded already
2021-01-09 16:46:27,782 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2021-01-09 16:46:27,782 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
2021-01-09 16:46:28,226 OES data year 2019 was found in /Users/lilian/Documents/jobhopper/api/data/bls/downloads/oesm19all/all_data_M_2019.csv. Loading it in.
2021-01-09 16:46:28,235 OES data year 2018 was found in /Users/lilian/Documents/jobhopper/api/data/bls/downloads/oesm18all/all_data_M_2018.csv. Loading it in.
2021-01-09 16:46:28,936 Successfully read OES data. Writing to the jobs_blsoes table
2021-01-09 16:46:56,377 Successfully loaded BLS data to Postgres!
Done with forward load
2021-01-09 16:46:56,401 Loading BLS wage and employment data to Postgres if a table_name is specified
2021-01-09 16:46:56,401 Connecting to Postgres DB via SQLAlchemy
2021-01-09 16:46:56,401 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2021-01-09 16:46:56,402 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2021-01-09 16:46:56,536 Download path: https://www.bls.gov//oes/special.requests/oesm18all.zip
2021-01-09 16:46:56,537 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm18all.zip if it has not been downloaded already
2021-01-09 16:46:56,554 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2021-01-09 16:46:56,555 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
2021-01-09 16:46:56,917 OES data year 2019 was found in /Users/lilian/Documents/jobhopper/api/data/bls/downloads/oesm19all/all_data_M_2019.csv. Loading it in.
2021-01-09 16:46:56,931 OES data year 2018 was found in /Users/lilian/Documents/jobhopper/api/data/bls/downloads/oesm18all/all_data_M_2018.csv. Loading it in.
2021-01-09 16:46:57,613 Saving unique SOC codes/descriptions to jobs_socdescription
2021-01-09 16:46:57,898 Filtering SOC codes to only include those in the source SOC for transitions data
2021-01-09 16:46:58,053 Unique SOC codes/descriptions saved!
Done with forward load
System check identified some issues:


WARNINGS:
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
	HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.

System check identified 1 issue (0 silenced).
...
----------------------------------------------------------------------
Ran 3 tests in 0.031s

OK
Destroying test database for alias 'default'...
```
* Checked `docker-compose up`

### CODE REVIEW

**Comment by jedpittman** [comment]
@l-cheung , I ran this in my environment as part of the docker process and I got this error. Does that reproduce for you?

C:\Users\jedpi\OneDrive\Documents\GitHub\lilian\jobhopper\docker>docker-compose up
Starting docker_db_1 ... done
Recreating docker_api_1 ... done
Recreating docker_frontend_1 ... done
Attaching to docker_db_1, docker_api_1, docker_frontend_1
api_1       | + env
api_1       | DB_PASSWORD=jobuser
api_1       | HOSTNAME=584b9e22a56b
api_1       | PYTHON_VERSION=3.7.9
api_1       | WAIT_HOSTS=db:5432
api_1       | PWD=/app
api_1       | DB_USER=jobuser
api_1       | HOME=/root
api_1       | LANG=C.UTF-8
api_1       | SECRET_KEY=ABx133o5tex
api_1       | GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
api_1       | DB_HOST=db
api_1       | SHLVL=1
api_1       | PYTHON_PIP_VERSION=20.2.4
api_1       | DB_NAME=jobhopper_dev
api_1       | PYTHON_GET_PIP_SHA256=2250ab0a7e70f6fd22b955493f7f5cf1ea53e70b584a84a32573644a045b4bfb
api_1       | PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/8283828b8fd6f1783daf55a765384e6d8d2c5014/get-pip.py
api_1       | PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
api_1       | _=/usr/bin/env
api_1       | + python manage.py migrate
db_1        |
db_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1        |
db_1        | 2021-01-09 19:26:15.002 UTC [1] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
db_1        | 2021-01-09 19:26:15.003 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 2021-01-09 19:26:15.004 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1        | 2021-01-09 19:26:15.008 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 2021-01-09 19:26:15.033 UTC [22] LOG:  database system was shut down at 2021-01-05 02:57:46 UTC
db_1        | 2021-01-09 19:26:15.042 UTC [1] LOG:  database system is ready to accept connections
frontend_1  |
frontend_1  | > frontend@1.0.0 start /app
frontend_1  | > react-scripts start
frontend_1  |
frontend_1  | sh: react-scripts: not found
frontend_1  | npm ERR! code ELIFECYCLE
frontend_1  | npm ERR! syscall spawn
frontend_1  | npm ERR! file sh
frontend_1  | npm ERR! errno ENOENT
frontend_1  | npm ERR! frontend@1.0.0 start: `react-scripts start`
frontend_1  | npm ERR! spawn ENOENT
frontend_1  | npm ERR!
frontend_1  | npm ERR! Failed at the frontend@1.0.0 start script.
frontend_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
frontend_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
frontend_1  |
frontend_1  | npm ERR! A complete log of this run can be found in:
frontend_1  | npm ERR!     /root/.npm/_logs/2021-01-09T19_26_17_481Z-debug.log
docker_frontend_1 exited with code 1
api_1       | System check identified some issues:
api_1       |
api_1       | WARNINGS:
api_1       | ?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
api_1       |   HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
api_1       | Traceback (most recent call last):
api_1       |   File "manage.py", line 22, in <module>
api_1       |     main()
api_1       |   File "manage.py", line 18, in main
api_1       |     execute_from_command_line(sys.argv)
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
api_1       |     utility.execute()
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
api_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
api_1       |     self.execute(*args, **cmd_options)
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
api_1       |     output = self.handle(*args, **options)
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 85, in wrapped
api_1       |     res = handle_func(*args, **kwargs)
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 92, in handle
api_1       |     executor = MigrationExecutor(connection, self.migration_progress_callback)
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
api_1       |     self.loader = MigrationLoader(self.connection)
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 53, in __init__
api_1       |     self.build_graph()
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 210, in build_graph
api_1       |     self.load_disk()
api_1       |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 112, in load_disk
api_1       |     migration_module = import_module(migration_path)
api_1       |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
api_1       |     return _bootstrap._gcd_import(name[level:], package, level)
api_1       |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
api_1       |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
api_1       |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
api_1       |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
api_1       |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
api_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api_1       |   File "/app/jobs/migrations/0011_auto_20201024_2201.py", line 4, in <module>
api_1       |     from api.data.scripts.sql_loader import load_bls_oes_to_sql
api_1       | ModuleNotFoundError: No module named 'api'
docker_api_1 exited with code 1

**Comment by l-cheung** [comment]
@jedpittman changed the paths. Hadn't checked docker!
```
api_1       | 2021-01-09 22:02:28,890 Loading BLS wage and employment data to Postgres if a table_name is specified
api_1       | 2021-01-09 22:02:28,893 Connecting to Postgres DB via SQLAlchemy
api_1       | 2021-01-09 22:02:28,899 Finding OES data download path from https://www.bls.gov/oes/tables.htm
api_1       | 2021-01-09 22:02:28,903 Finding OES data download path from https://www.bls.gov/oes/tables.htm
api_1       | 2021-01-09 22:02:29,183 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
api_1       | 2021-01-09 22:02:29,185 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
api_1       | 2021-01-09 22:02:29,192 Download path: https://www.bls.gov//oes/special.requests/oesm18all.zip
api_1       | 2021-01-09 22:02:29,193 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm18all.zip if it has not been downloaded already
api_1       | 2021-01-09 22:02:29,953 OES data year 2019 was found in /app/data/bls/downloads/oesm19all/all_data_M_2019.csv. Loading it in.
api_1       | 2021-01-09 22:02:30,050 OES data year 2018 was found in /app/data/bls/downloads/oesm18all/all_data_M_2018.csv. Loading it in.
api_1       | 2021-01-09 22:02:30,942 Successfully read OES data. Writing to the jobs_blsoes table
api_1       | 2021-01-09 22:03:47,256 Successfully loaded BLS data to Postgres!
api_1       | 2021-01-09 22:03:47,297 Loading BLS wage and employment data to Postgres if a table_name is specified
api_1       | 2021-01-09 22:03:47,297 Connecting to Postgres DB via SQLAlchemy
api_1       | 2021-01-09 22:03:47,299 Finding OES data download path from https://www.bls.gov/oes/tables.htm
api_1       | 2021-01-09 22:03:47,300 Finding OES data download path from https://www.bls.gov/oes/tables.htm
api_1       | 2021-01-09 22:03:47,579 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
api_1       | 2021-01-09 22:03:47,580 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
api_1       | 2021-01-09 22:03:47,687 Download path: https://www.bls.gov//oes/special.requests/oesm18all.zip
api_1       | 2021-01-09 22:03:47,689 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm18all.zip if it has not been downloaded already
api_1       | 2021-01-09 22:03:48,598 OES data year 2018 was found in /app/data/bls/downloads/oesm18all/all_data_M_2018.csv. Loading it in.
api_1       | 2021-01-09 22:03:48,611 OES data year 2019 was found in /app/data/bls/downloads/oesm19all/all_data_M_2019.csv. Loading it in.
api_1       | 2021-01-09 22:03:49,384 Saving unique SOC codes/descriptions to jobs_socdescription
api_1       | 2021-01-09 22:03:49,941 Filtering SOC codes to only include those in the source SOC for transitions data
api_1       | 2021-01-09 22:03:50,181 Unique SOC codes/descriptions saved!
api_1       | Operations to perform:
api_1       |   Apply all migrations: admin, auth, contenttypes, jobs, sessions
api_1       | Running migrations:
api_1       |   Applying contenttypes.0001_initial... OK
api_1       |   Applying auth.0001_initial... OK
api_1       |   Applying admin.0001_initial... OK
api_1       |   Applying admin.0002_logentry_remove_auto_add... OK
api_1       |   Applying admin.0003_logentry_add_action_flag_choices... OK
api_1       |   Applying contenttypes.0002_remove_content_type_name... OK
api_1       |   Applying auth.0002_alter_permission_name_max_length... OK
api_1       |   Applying auth.0003_alter_user_email_max_length... OK
api_1       |   Applying auth.0004_alter_user_username_opts... OK
api_1       |   Applying auth.0005_alter_user_last_login_null... OK
api_1       |   Applying auth.0006_require_contenttypes_0002... OK
api_1       |   Applying auth.0007_alter_validators_add_error_messages... OK
api_1       |   Applying auth.0008_alter_user_username_max_length... OK
api_1       |   Applying auth.0009_alter_user_last_name_max_length... OK
api_1       |   Applying auth.0010_alter_group_name_max_length... OK
api_1       |   Applying auth.0011_update_proxy_permissions... OK
api_1       |   Applying auth.0012_alter_user_first_name_max_length... OK
api_1       |   Applying jobs.0001_initial... OK
api_1       |   Applying jobs.0002_occupationtransitions... OK
api_1       |   Applying jobs.0006_blsoesfakes... OK
api_1       |   Applying jobs.0007_stateabbpairs... OK
api_1       |   Applying jobs.0008_auto_20201006_AddStateData... OK
api_1       |   Applying jobs.0009_auto_20201013_2033... show db default
api_1       | Processing data from csv; This will take a few minutes.
api_1       | <connection object at 0x7f2f76f21b90; dsn: 'user=jobuser password=xxx dbname=jobhopper_dev host=db port=5432', closed: 0>
api_1       | jobhopper_dev
api_1       | done with forward load
api_1       |  OK
api_1       |   Applying jobs.0010_blsoes... OK
api_1       |   Applying jobs.0011_auto_20201024_2201...Done with forward load
api_1       |  OK
api_1       |   Applying jobs.0012_socdescription... OK
api_1       |   Applying jobs.0013_auto_20201107_2201...Done with forward load
api_1       |  OK
api_1       |   Applying sessions.0001_initial... OK
api_1       | + python manage.py runserver 0.0.0.0:8000
api_1       | Watching for file changes with StatReloader
```

**Review by alexjball — APPROVED** [review]
Works great, thanks! Just have two questions

- Where do we configure our tests? is the test command part of Django, and automatically tests migrations?
- Since this is updating the existing migrations, do we need to effectively drop the database and regenerate it on the deployment side?

**Comment by jedpittman** [comment]
Merging per Alex's comment above

**Comment by l-cheung** [comment]
Django comes with out-of-the-box testing capabilities per https://adamj.eu/tech/2020/09/05/what-happens-when-you-run-manage.py-test/ so tests will at minimum create a test database and run migrations. Testing also automatically looks for test cases in files beginning with `test` 

& I think so. We could back up a few migrations and just re-run the last few, or re-run all migrations, which effectively drops and regenerates the database

**Pull request merged**
