### PR TITLE
ISS 136 - continuous deployment for frontend on develop branch

### PR DESCRIPTION
**Pull request by alexjball**
Deployed site: https://jobhopper-dev.web.app/ (placeholder page, #198 and #195 implement the actual site) 
[Successful CD run](https://github.com/alexjball/jobhopper/runs/1466086908?check_suite_focus=true)

Use firebase hosting to deploy the site. I created a [jobhopper-dev](https://console.firebase.google.com/u/0/project/jobhopper-dev/hosting/main) project that we can manage the dev environment under.

When we decide how we want to host production, we can add another workflow for that. Firebase will still probably be useful for hosting develop and other test environments.

Here are the steps to get CD set up for the codeforboston repo:

- Merge this PR
- Someone with admin role on the CFB repo needs to add a secret named `FIREBASE_TOKEN` under the repo settings. I can provide the value of the secret
- Add project leads as admins to the firebase project

### CODE REVIEW

**Comment by timtraversy** [comment]
This is great, I like Firebase! It would be cool if we could use the frontend Dockerfile for the GitHub workflow: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action.

Then we'd guarantee it's built the same way for Firebase as for our development machines (same node version, base image).

Just googled those docs now, there might be a better way to set it up.

**Comment by alexjball** [comment]
Hey Tim, the current frontend Dockerfile is built for development since it uses `npm install` and runs the dev server by default. We would want to create a separate build image that creates the static production site with npm ci and npm run build, then grab the site content from the image and publish to firebase. The build itself is simple and only depends on the source tree and node version, both of which are managed for us by Github Actions. So I'm not sure we would gain much by using Docker to build the site.

**Comment by timtraversy** [comment]
Yeah you're right, the benefits aren't huge at this stage

**Comment by jedpittman** [comment]
@alexjball , I can add the secret and we can sort out the rest of the details via slack. Thanks

**Pull request merged**
