### PR TITLE
Issue 130

### PR DESCRIPTION
**Pull request by l-cheung**
* Load BLS data into Django model, using `bls_oes` SQL table
* Downloads table if it doesn't exist
* Creates BlsOes model

### CODE REVIEW

**Comment by jedpittman** [comment]
I am reviewing this...

**Comment by jedpittman** [comment]
This looks like it is not working. 
In general, I'd expect to be able to run migration forward and backward (as much as I want) and then also to run testing. The testing is what broke:

(venv) C:\Users\jedpi\OneDrive\Documents\GitHub\lilian\jobhopper>python manage.py test
Creating test database for alias 'default'...
 show db default
all tables available ['auth_group', 'auth_group_permissions', 'auth_permission', 'auth_user', 'auth_user_groups', 'auth_user_user_permissions', 'django_admin_log', 'django_content_type', 'django_migrations', 'jobs_blsoes', 'jobs_blsoesfakes', 'jobs_jobclass', 'jobs_occupationtransitions', 'jobs_socs', 'jobs_stateabbpairs']
2020-10-20 16:37:50,334 Loading BLS wage and employment data to Postgres
2020-10-20 16:37:50,334 Connecting to Postgres DB via SQLAlchemy
2020-10-20 16:37:50,363 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-20 16:37:50,664 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-10-20 16:37:50,665 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-10-20 16:37:53,078 Downloading to directory C:\Users\jedpi\OneDrive\Documents\GitHub\lilian\jobhopper\data\bls\downloads
2020-10-20 16:37:53,588 Files found: ['oesm19all/all_data_M_2019.xlsx']
2020-10-20 16:37:53,588 Check the data/bls/downloads directory for the xlsx file downloaded
2020-10-20 16:37:53,588 Reading Excel file: oesm19all/all_data_M_2019.xlsx --- This may take a few minutes.
2020-10-20 16:40:05,584 Successfully loaded BLS data to Postgres!
<connection object at 0x0000015F4BC396A8; dsn: 'user=jobuser password=xxx dbname=test_jobhopperdatabase host=127.0.0.1 port=5432', closed: 0>
test_jobhopperdatabase
done with forward load
Traceback (most recent call last):
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "bls_oes" does not exist
LINE 6:                     FROM bls_oes;
                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\commands\test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\commands\test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\test\runner.py", line 695, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\test\runner.py", line 616, in setup_databases
    self.parallel, **kwargs
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\test\utils.py", line 174, in setup_databases
    serialize=connection.settings_dict['TEST'].get('SERIALIZE', True),
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\backends\base\creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\core\management\commands\migrate.py", line 245, in handle
    fake_initial=fake_initial,
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\migrations\operations\special.py", line 105, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\migrations\operations\special.py", line 126, in _run_sql
    schema_editor.execute(sql, params=params)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\backends\base\schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\JedJobhopper\jobhopper\venv\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "bls_oes" does not exist
LINE 6:                     FROM bls_oes;

**Comment by l-cheung** [comment]
Pushed a fix for the `manage.py test` failure. Output: 
```
Creating test database for alias 'default'...
2020-10-24 20:36:58,048 Loading BLS wage and employment data to Postgres if a table_name is specified
2020-10-24 20:36:58,048 Connecting to Postgres DB via SQLAlchemy
2020-10-24 20:36:58,060 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-24 20:36:58,277 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-10-24 20:36:58,278 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-10-24 20:36:58,446 OES data year 2019 was found in /Users/lilian/Documents/jobhopper/data/bls/downloads/oesm19all/all_data_M_2019.xlsx. Loading it in.
2020-10-24 20:39:13,973 Successfully loaded BLS data to Postgres!
Done with forward load
System check identified no issues (0 silenced).
.2020-10-24 20:39:14,297 Not Found: /jobs/api/leads
...
----------------------------------------------------------------------
Ran 4 tests in 0.085s

OK
```

Reverse migration:
```
(jobhopper) jobhopper % python manage.py migrate jobs zero
Operations to perform:
  Unapply all migrations: jobs
Running migrations:
  Rendering model states... DONE
  Unapplying jobs.0011_auto_20201024_2201...Removing source data
 OK
  Unapplying jobs.0010_blsoes... OK
  Unapplying jobs.0009_auto_20201013_2033... OK
  Unapplying jobs.0008_auto_20201006_AddStateData... OK
  Unapplying jobs.0007_stateabbpairs... OK
  Unapplying jobs.0006_blsoesfakes... OK
  Unapplying jobs.0005_auto_20200914_1220... OK
  Unapplying jobs.0004_auto_20200909_1255... OK
  Unapplying jobs.0003_auto_20200909_1254... OK
  Unapplying jobs.0002_occupationtransitions... OK
  Unapplying jobs.0001_initial... OK
```

Forward migration:
```
(jobhopper) jobhopper % python manage.py migrate jobs
Operations to perform:
  Apply all migrations: jobs
Running migrations:
  Applying jobs.0001_initial... OK
  Applying jobs.0002_occupationtransitions... OK
  Applying jobs.0003_auto_20200909_1254... OK
  Applying jobs.0004_auto_20200909_1255... OK
  Applying jobs.0005_auto_20200914_1220... OK
  Applying jobs.0006_blsoesfakes... OK
  Applying jobs.0007_stateabbpairs... OK
  Applying jobs.0008_auto_20201006_AddStateData... OK
  Applying jobs.0009_auto_20201013_2033... OK
  Applying jobs.0010_blsoes... OK
2020-10-24 22:05:08,606 Loading BLS wage and employment data to Postgres if a table_name is specified
2020-10-24 22:05:08,606 Connecting to Postgres DB via SQLAlchemy
2020-10-24 22:05:08,617 Finding OES data download path from https://www.bls.gov/oes/tables.htm
2020-10-24 22:05:11,823 Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
2020-10-24 22:05:11,824 Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip if it has not been downloaded already
2020-10-24 22:05:11,929 OES data year 2019 was found in /Users/lilian/Documents/jobhopper/data/bls/downloads/oesm19all/all_data_M_2019.csv. Loading it in.
2020-10-24 22:05:12,271 Successfully read OES data. Writing to the jobs_blsoes table
2020-10-24 22:05:42,869 Successfully loaded BLS data to Postgres!
  Applying jobs.0011_auto_20201024_2201...Done with forward load
 OK
```

Notes on troubleshooting:
* The error seems related to using legacy databases/tables defined outside of Django. Migrations work, but tests do not: https://medium.com/@phamthuc/testing-with-the-legacy-database-in-django-3be84786daba
* It's possible to get around that by adding a `BlsOes` model in Django, running `python manage.py makemigrations` to create the model in the next migration, and loading the data directly into that model

**Comment by jedpittman** [comment]
I see the issue with the two branches pointed out by @l-cheung and I am fixing. Step 1 was to get develop branch updated; next I'm merging this to V1.1.0 and making sure that there are no further issues.

**Pull request merged**
