### PR TITLE
dropdown selection w no observations gives message

### LINKED ISSUE #267: Ensure that dropdown selection of soc with no observations has the correct message
Context: in the demo, we had some socs with no data.

After the user makes a selection, if it is an occupation for which we do not have data, display the text: “We do not have data on occupational transitions for this occupation”

(Note we never expect this to happen, but we want to build it in just in case.)

### PR DESCRIPTION
**Pull request by jkoren**
Closes #267

### CODE REVIEW

**Comment by jedpittman** [comment]
@jkoren please take another look. If you run the npm command to run all tests (see the package.json for the command), you should get failures similar to the checks that are failing on this PR:

Transitions
    ✕ updates the list of transitions (2ms)
    ✕ handles update error (1ms)
    ✕ handles abortions (3ms)

Fix those and then push the updated code and once the tests pass we'll review. Also make sure to do a git pull from the develop branch so that you have the latest code and any conflicts get merged before you push again. Thanks!

**Comment by jkoren** [comment]
@jedpittman @alexjball and I saw that the tests failed last night when we submitted, but time ran out to fix.  Alex asked me to look at the tests to make sure they are still appropriate for the fix we made.

**Comment by jkoren** [comment]
I updated the tests to reflect new expectations and now all pass.

**Comment by jedpittman** [comment]
@jkoren nice work. Going forward, on your commits, please include the issue, e.g. ISS-267 did some work. This helps once we merge to master so that we don't lose track of which commit each change belongs to.

**Comment by jkoren** [comment]
@jedpittman great. so when I do commit, make the message something like `commit -m "ISS-267 added message when dropdown selection has no observations"?`

**Comment by jedpittman** [comment]
yes perfect

**Pull request merged**
