### PR TITLE
Issue #65: Load BLS Wage/Employment data and SOC transitions data (Burning Glass) to Postgres

### PR DESCRIPTION
**Pull request by l-cheung**
* Load SOC transitions data to postgres
* Load BLS wage/employment data to postgres
* Configure postgres based on environment variables from updated readme
* Move readme file & consolidated .txt readme with general readme
* Minor reorganizing

### CODE REVIEW

**Comment by jedpittman** [comment]
@l-cheung I'm going to try to take a pass at this review now.

**Comment by jedpittman** [comment]
Just to close the loop with you @l-cheung , I had the following error in my environment -- certainly could be something environmental on my side -- but just in case you had a solution, here's the stack trace: 
(venv) C:\Users\jedpi\OneDrive\Documents\GitHub\jobhopper>python data\load_jobhopper_data.py
INFO:root:Loading occupation transitions (Burning Glass) data to Postgres
INFO:root:Connecting to Postgres DB via SQLAlchemy
INFO:root:Loading BLS wage and employment data to Postgres
INFO:root:Connecting to Postgres DB via SQLAlchemy
INFO:root:Finding OES data download path from https://www.bls.gov/oes/tables.htm
INFO:root:Download path: https://www.bls.gov//oes/special.requests/oesm19all.zip
INFO:root:Downloading OES data from https://www.bls.gov//oes/special.requests/oesm19all.zip
Traceback (most recent call last):
  File "data\load_jobhopper_data.py", line 35, in <module>
    run()
  File "data\load_jobhopper_data.py", line 31, in run
    load_bls_oes_to_sql()
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\jobhopper\data\scripts\sql_loader.py", line 64, in load_bls_oes_to_sql
    bls_oes_data = OESDataDownloader().download_oes_data("2019")
  File "C:\Users\jedpi\OneDrive\Documents\GitHub\jobhopper\data\bls\oes_data_downloader.py", line 72, in download_oes_data
    format = 'zip')
  File "C:\Users\jedpi\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 993, in unpack_archive
    func(filename, extract_dir, **dict(format_info[2]))
  File "C:\Users\jedpi\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 899, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: C:\Users\jedpi\AppData\Local\Temp\tmp0sg1bbyw is not a zip file

**Comment by l-cheung** [comment]
Interesting! I'll look into it. Unable to reproduce on macOS, but will try with Windows/Linux

**Comment by l-cheung** [comment]
Reproduced with Windows. Works on Linux + MacOS for me. I'll take a shot at debugging

**Comment by jedpittman** [comment]
Yeah I was able to get far enough to handle working around it (See the other merge request i put in for you. So, if you're game to review that and then we can reconcile any changes etc as needed, I think that will work...)

**Comment by l-cheung** [comment]
Thanks for taking a look! Added comments to the other MR. The workaround works for me as long as Postgres is set up with that specific user. Assuming we'll add it to the readme + move to a hosted DB eventually, so that should be fine for now. Linked to some other changes on my forked repo in that MR so we can reconcile changes

**Comment by jedpittman** [comment]
Closing this pull request as it was merged in other pull requests.

**Pull request closed without merging**
